import { css } from '@emotion/css';

export default {
  buttonStyle: css({
    alignItems: 'center',
    backgroundClip: 'padding-box',
    backgroundColor: '#fa6400',
    border: '1px solid transparent',
    borderRadius: '.25rem',
    boxShadow: 'rgba(0, 0, 0, 0.02) 0 1px 3px 0',
    boxSizing: 'border-box',
    color: '#fff',
    cursor: 'pointer',
    display: 'inline-flex',
    fontSize: '16px',
    fontWeight: '600',
    justifyContent: 'center',
    lineHeight: '1.25',
    margin: '0',
    minHeight: '3rem',
    padding: 'calc(.875rem - 1px) calc(1.5rem - 1px)',
    position: 'relative',
    textDecoration: 'none',
    transition: 'all 250ms',
    userSelect: 'none',
    touchAction: 'manipulation',
    verticalAlign: 'baseline',
    width: 'auto',
  }),
}
